    .import VDP_REG
    .import VDP_VRAM

    .import VDP_TEXT_PATTERNS_START
    .import VDP_TEXT_PATTERNS_END
    .import VDP_PATTERN_TABLE_BASE
    .import VDP_COLOR_TABLE_BASE

    .import vdp_init_text_mode
    .import vdp_init_graphics1_mode
    .import vdp_initialize_text_pattern_table
    .import vdp_clear_screen
    .import vdp_enable_display

    .import vdp_vram_write_buffer
    .import vdp_vram_read_buffer
    .import vdp_fill_color
    .import vdp_hide_sprites

    .import vdp_set_border_color
