PROJECT_NAME=18_core_program
BUILD_TYPE=rom

ASM_SOURCES=main.s
C_SOURCES=
COMMON_DEPS=utils.o lcd.o zeropage.o via.o blink.o core.o acia.o syscalls.o modem.o keyboard.o

include ../../common/makefile

