PROJECT_NAME=22_modem_test
BUILD_TYPE=rom

ASM_SOURCES=modem_test.s
C_SOURCES=
COMMON_DEPS=utils.o lcd.o zeropage.o via.o blink.o core.o acia.o modem.o keyboard.o syscalls.o string.o

include ../../common/makefile

